2019-11-13 22:13:44,946	configurator.py	ERROR	could not connect to server: Connection refused
	Is the server running on host "34.89.239.19" and accepting
	TCP/IP connections on port 5432?

2019-11-13 22:46:49,523	configurator.py	INFO	Successfully connected to psql...
2019-11-13 22:49:13,530	configurator.py	INFO	Successfully connected to psql...
2019-11-13 22:50:28,430	configurator.py	INFO	Successfully connected to psql...
2019-11-13 22:50:28,492	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) 
                   VALUES(2, '0.0.0.0', 502, 1, 'sdm630', 'test_energy_meter');
2019-11-13 22:54:05,349	configurator.py	INFO	Successfully connected to psql...
2019-11-13 22:54:05,442	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) 
                   VALUES(2, '0.0.0.0', 502, 1, 'sdm630', 'test_energy_meter');
2019-11-13 22:58:17,585	configurator.py	INFO	Successfully connected to psql...
2019-11-13 22:58:46,885	configurator.py	INFO	Successfully connected to psql...
2019-11-13 22:59:59,106	configurator.py	INFO	Successfully connected to psql...
2019-11-13 23:00:45,631	configurator.py	INFO	Successfully connected to psql...
2019-11-13 23:00:45,725	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) VALUES(%s, %s, %s, %s, %s, %s);
2019-11-13 23:02:05,727	configurator.py	INFO	Successfully connected to psql...
2019-11-13 23:02:05,821	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) VALUES(%s, %s, %s, %s, %s, %s);
2019-11-13 23:02:36,985	configurator.py	INFO	Successfully connected to psql...
2019-11-13 23:02:37,080	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) VALUES(%s, %s, %s, %s, %s, %s);
2019-11-13 23:05:52,872	configurator.py	INFO	Successfully connected to psql...
2019-11-13 23:05:52,982	configurator.py	INFO	SELECT * FROM energy_meters;
2019-11-13 23:06:11,932	configurator.py	INFO	Successfully connected to psql...
2019-11-13 23:06:11,993	configurator.py	INFO	SELECT * FROM energy_meters;
2019-11-13 23:08:39,209	configurator.py	INFO	Successfully connected to psql...
2019-11-13 23:08:39,302	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) 
                   VALUES(2, '0.0.0.0', 502, 1, 'sdm630', 'test_energy_meter');
2019-11-13 23:21:10,226	configurator.py	INFO	Successfully connected to psql...
2019-11-13 23:22:37,666	configurator.py	INFO	Successfully connected to psql...
2019-11-13 23:27:10,598	configurator.py	INFO	Successfully connected to psql...
2019-11-13 23:28:00,094	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) 
                   VALUES(2, '0.0.0.0', 502, 1, 'sdm630', 'test_energy_meter');
2019-11-13 23:31:07,330	configurator.py	INFO	Successfully connected to psql...
2019-11-13 23:32:00,095	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) 
                   VALUES(2, '0.0.0.0', 502, 1, 'sdm630', 'test_energy_meter');
2019-11-13 23:47:42,461	configurator.py	ERROR	could not connect to server: Connection refused
	Is the server running on host "34.89.239.19" and accepting
	TCP/IP connections on port 5432?

2019-11-13 23:49:39,628	configurator.py	INFO	Successfully connected to psql...
2019-11-13 23:50:00,098	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) 
                   VALUES(2, '0.0.0.0', 502, 1, 'sdm630', 'test_energy_meter');
2019-11-13 23:51:00,002	configurator.py	ERROR	terminating connection due to administrator command
SSL connection has been closed unexpectedly

2019-11-13 23:51:00,003	configurator.py	ERROR	Disconected with psql, retrying...
2019-11-13 23:51:00,035	configurator.py	ERROR	could not connect to server: Connection refused
	Is the server running on host "34.89.239.19" and accepting
	TCP/IP connections on port 5432?

2019-11-13 23:55:30,569	configurator.py	ERROR	could not connect to server: Connection refused
	Is the server running on host "34.89.239.19" and accepting
	TCP/IP connections on port 5432?

2019-11-13 23:55:30,570	configurator.py	INFO	Exiting...
2019-11-13 23:55:54,487	configurator.py	INFO	Successfully connected to psql...
2019-11-13 23:56:00,100	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) 
                   VALUES(2, '0.0.0.0', 502, 1, 'sdm630', 'test_energy_meter');
2019-11-13 23:57:00,002	configurator.py	ERROR	terminating connection due to administrator command
SSL connection has been closed unexpectedly

2019-11-13 23:57:00,003	configurator.py	ERROR	Disconected with psql, retrying...
2019-11-13 23:57:00,035	configurator.py	ERROR	could not connect to server: Connection refused
	Is the server running on host "34.89.239.19" and accepting
	TCP/IP connections on port 5432?

2019-11-13 23:57:00,035	configurator.py	INFO	Exiting...
2019-11-14 00:01:37,205	configurator.py	INFO	Successfully connected to psql...
2019-11-14 00:02:00,096	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) 
                   VALUES(2, '0.0.0.0', 502, 1, 'sdm630', 'test_energy_meter');
2019-11-14 00:03:00,002	configurator.py	ERROR	terminating connection due to administrator command
SSL connection has been closed unexpectedly

2019-11-14 00:03:00,003	configurator.py	ERROR	Disconected with psql, retrying...
2019-11-14 00:03:00,033	configurator.py	ERROR	could not connect to server: Connection refused
	Is the server running on host "34.89.239.19" and accepting
	TCP/IP connections on port 5432?

2019-11-14 00:03:00,034	configurator.py	INFO	Exiting...
2019-11-14 00:05:37,180	configurator.py	INFO	Successfully connected to psql...
2019-11-14 00:06:00,099	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) 
                   VALUES(2, '0.0.0.0', 502, 1, 'sdm630', 'test_energy_meter');
2019-11-14 00:07:00,003	configurator.py	ERROR	terminating connection due to administrator command
SSL connection has been closed unexpectedly

2019-11-14 00:07:00,003	configurator.py	ERROR	Disconected with psql, retrying...
2019-11-14 00:07:00,036	configurator.py	ERROR	could not connect to server: Connection refused
	Is the server running on host "34.89.239.19" and accepting
	TCP/IP connections on port 5432?

2019-11-14 00:07:00,037	configurator.py	INFO	Exiting...
2019-11-14 00:08:58,301	configurator.py	ERROR	could not connect to server: Connection refused
	Is the server running on host "34.89.239.19" and accepting
	TCP/IP connections on port 5432?

2019-11-14 00:09:15,418	configurator.py	INFO	Successfully connected to psql...
2019-11-14 00:10:00,094	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) 
                   VALUES(2, '0.0.0.0', 502, 1, 'sdm630', 'test_energy_meter');
2019-11-14 00:11:00,002	configurator.py	ERROR	terminating connection due to administrator command
SSL connection has been closed unexpectedly

2019-11-14 00:11:00,003	configurator.py	ERROR	Unexpected psql disconnect, exiting...
2019-11-14 00:11:51,426	configurator.py	ERROR	could not connect to server: Connection refused
	Is the server running on host "34.89.239.19" and accepting
	TCP/IP connections on port 5432?

2019-11-14 00:12:15,208	configurator.py	ERROR	Cannot connect to psql...
2019-11-14 00:12:32,747	configurator.py	INFO	Successfully connected to psql...
2019-11-14 00:13:00,094	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) 
                   VALUES(2, '0.0.0.0', 502, 1, 'sdm630', 'test_energy_meter');
2019-11-14 00:14:00,001	configurator.py	ERROR	terminating connection due to administrator command
SSL connection has been closed unexpectedly

2019-11-14 00:14:00,002	configurator.py	ERROR	Unexpected psql disconnect, exiting...
2019-11-14 00:14:54,625	configurator.py	INFO	Successfully connected to psql...
2019-11-14 00:15:00,099	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) 
                   VALUES(2, '0.0.0.0', 502, 1, 'sdm630', 'test_energy_meter');
2019-11-14 00:16:00,004	configurator.py	ERROR	Unexpected psql disconnect, exiting...
2019-11-14 00:19:49,415	configurator.py	ERROR	Cannot connect to psql...
2019-11-14 00:19:58,952	configurator.py	INFO	Successfully connected to psql...
2019-11-14 00:20:00,099	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) 
                   VALUES(2, '0.0.0.0', 502, 1, 'sdm630', 'test_energy_meter');
2019-11-14 00:20:27,679	configurator.py	INFO	Successfully connected to psql...
2019-11-14 00:21:00,095	configurator.py	INFO	INSERT INTO energy_meters(location_id, host, port, slaveaddress, energy_meter_id, description) 
                   VALUES(2, '0.0.0.0', 502, 1, 'sdm630', 'test_energy_meter');
